### ISSUE TITLE
'CanbusLast': None

### ISSUE THREAD

**Issue by mvroosmalen1970** [TheBazeman/MijnKia#1]
Hoi 

vandaag getest en krijg de volgende error:
<Response [200]>
{u'SelectedCar': {u'Model': u'Kia e-Niro', u'PathToModelImage': u'/nl/mijnkia/-/media/application/mykia-platform/carbase-images/niro-de/niro-ev.ashx', u'ModelCode': None}, u'CanbusLast': None}
200
Traceback (most recent call last):
  File "/home/osmc/MijnKia/MijnKia.py", line 168, in <module>
    for attribute in HTTPresponse.json()['CanbusLast']:
TypeError: 'NoneType' object is not iterable

is dit een normale output (in test modus) : **'CanbusLast': None}**
of  is het auto model onjuist en hoe vind ik deze?
Kia;e-Niro;64kWh geeft dezelfde fout melding....

mvg Mark

**Comment by TheBazeman** [comment]
Hoi Mark,

Nee dat klopt idd niet, die moet gevuld zijn. Bij mij werkt hij gewoon nog, logt hij wel goed in en werkt het op de site wel goed? Mijn e-Niro is trouwens van eind 2019

https://www.kia.com/nl/mijnkia/ --> inloggen en dan in dezelfde sessie navigeren naar https://www.kia.com/nl/webservices/mykia/connectedcar.asmx/GetCanbusData

Geeft bij mij:
***@***.***D73A7D.CADE7AA0]

Met vriendelijke groet,

Bas Bahlmann

Van: mvroosmalen1970 ***@***.***
Verzonden: zaterdag 24 april 2021 22:03
Aan: TheBazeman/MijnKia ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [TheBazeman/MijnKia] 'CanbusLast': None (#1)


Hoi

vandaag getest en krijg de volgende error:
<Response [200]>
{u'SelectedCar': {u'Model': u'Kia e-Niro', u'PathToModelImage': u'/nl/mijnkia/-/media/application/mykia-platform/carbase-images/niro-de/niro-ev.ashx', u'ModelCode': None}, u'CanbusLast': None}
200
Traceback (most recent call last):
File "/home/osmc/MijnKia/MijnKia.py", line 168, in
for attribute in HTTPresponse.json()['CanbusLast']:
TypeError: 'NoneType' object is not iterable

is dit een normale output (in test modus) : 'CanbusLast': None}
of is het auto model onjuist en hoe vind ik deze?
Kia;e-Niro;64kWh geeft dezelfde fout melding....

mvg Mark

**Comment by mvroosmalen1970** [comment]
Hoi Bas,
Ik heb een oplossing met BlUVO, deze werkt wel met mijn Kia eNiro2021
:-). Misschien heb je er iets aan anders toch bedankt voor het checken
:-)
Mark
