### ISSUE TITLE
https://www.kia.com/nl/webservices/mykia/connectedcar.asmx/GetCanbusData niet meer bruikbaar?

### ISSUE THREAD

**Issue by gvrawake** [TheBazeman/MijnKia#3]
Kan het zijn dat het niet meer werkt omdat Kia is overgestapt op een andere url? Bij mijnkia log je tegenwoordig in op https://mijnkia.nl/dashboard/, en een curl naar bovengenoemde url geeft UNAVAILABLE terug (Wegens onderhoud is onze website momenteel niet beschikbaar.).

**Comment by JahFyahh** [comment]
I just created a pull request to use the new site.
I have no knowledge about Influx so only updated the MQTT part for the moment.
Maybe @TheBazeman can have a look at the Influx part, using the MQTT part.

**Comment by TheBazeman** [comment]
Yep, fixed InfluxDB and ABRP part

**Comment by TheBazeman** [comment]
Bij mij werkt hij nog prima!

Groeten,
Bas

Van: gvrawake ***@***.***
Verzonden: vrijdag 3 juni 2022 10:45
Aan: TheBazeman/MijnKia ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [TheBazeman/MijnKia] https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fwww.kia.com%2Fnl%2Fwebservices%2Fmykia%2Fconnectedcar.asmx%2FGetCanbusData&data=eJxNi8EOgjAQRL-G3mwEjZFDD0aCN42fsF1WIbZb0haBv3e5mUwymTczaE5ViTWWtjy_qFadsdA7D8yanfLmuYwtQtjV9-6h...


Kan het zijn dat het niet meer werkt omdat Kia is overgestapt op een andere url? Bij mijnkia log je tegenwoordig in op https://mijnkia.nl/dashboard/<https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fmijnkia.nl%2Fdashboard%2F&data=eJxNi7EOAiEQRL8GOi9yGiPFFjZXavyEZTkFhYUAl-jfu6XJFDNv8ghOsyFLxpnzY7Xag8OQMjJPnHSG-6cuhGVnr_6mO3Bpa01fddw_4wibm6hk3cTpgv7NDcIYtavDRc2LJMcXvyPKJcNjD65g89J_1z0rEg%25%25>, en een curl naar bovengenoemde url geeft UNAVAILABLE terug (Wegens onderhoud is onze website momenteel niet beschikbaar.).
